#!/bin/bash

if [[ -z "$1" ]]; then
    echo "usage: git date-diff [<options>] <from> [<to>]"
    exit 1
fi

for arg in "$@"; do
    if [[ $arg =~ ^--?.+$ ]]; then
        options+=("$arg")
    elif [[ -z $from ]]; then
        from="$arg"
    elif [[ -z $to ]]; then
        to="$arg"
    fi
done

revisions=($(git rev-list --no-merges --since="$from" --until="${to:-HEAD}" HEAD))
total=${#revisions[*]}
from=${revisions[*]:(-1)}

if [[ $total == 1 ]]; then
    to="$from"
    from="$to^"
else
    to="${revisions[0]}"
fi

git diff "${options[@]}" "$from" "$to"
