#!/bin/bash

set -e

function info() {
    echo
    echo -e "\033[34;1m# \033[31;1m$*\033[0m"
}

version=$1

if [ -z "$version" ]; then
    local_version="v$(git --version | grep -Eo '[0-9.]+')"
    remote_version="$(git ls-remote git://git.kernel.org/pub/scm/git/git.git | grep -v '\-rc' | grep -Eo 'v[0-9.]+' | uniq | tail -n 1)"
    if [ "$local_version" = "$remote_version" ]; then
        echo "You already have the latest git version: $local_version"
        exit
    fi
    version="${remote_version/v/}"
    info "Auto-upgrading to the latest git version: ${remote_version}"
fi

# Enable `git grep -P`
export USE_LIBPCRE=yes

# Create temp dir to work in
info "Creating temporary directory"
tmp_dir="$(mktemp -d)"
cd "$tmp_dir"
echo "$tmp_dir"
# Git core
info "Downloading git-${version}.tar.gz"
curl -sS -O "https://www.kernel.org/pub/software/scm/git/git-${version}.tar.gz"
info "Extracting git-${version}.tar.gz"
tar zxvf "git-${version}.tar.gz"
info "Configuring git-${version}"
cd "git-${version}"
./configure --prefix=/usr/local --with-gitconfig=/etc/gitconfig
info "Making git-${version}"
make
info "Installing git-${version}"
sudo make install
# Bash completion
sudo cp contrib/completion/git-completion.bash /etc/bash_completion.d/git
# Man pages
info "Downloading git-manpages-${version}.tar.gz"
curl -sS -O "https://www.kernel.org/pub/software/scm/git/git-manpages-${version}.tar.gz"
info "Extracting git-manpages-${version}.tar.gz"
sudo mkdir -p /usr/local/share/man
sudo tar zxvf "git-manpages-${version}.tar.gz" -C /usr/local/share/man
sudo chmod -R 755 /usr/local/share/man /etc/bash_completion.d
info "Done"

echo
