#!/bin/bash -e

if [[ -z $1 ]]; then
    echo "Must supply Git version to install (e.g. 2.2.1)"
    exit 1
fi

function info() {
    echo
    echo -e "\033[34;1m# \033[31;1m$*\033[0m"
}

version=$1

# Create temp dir to work in
info "Creating temporary directory"
tmp_dir="$(mktemp -d)"
cd "$tmp_dir"
echo "$tmp_dir"
# Git core
info "Downloading git-${version}.tar.gz"
curl -sS -O "https://www.kernel.org/pub/software/scm/git/git-${version}.tar.gz"
info "Extracting git-${version}.tar.gz"
tar zxvf "git-${version}.tar.gz"
info "Configuring git-${version}"
cd "git-${version}"
./configure --prefix=/usr --with-gitconfig=/etc/gitconfig
info "Making git-${version}"
make
info "Installing git-${version}"
sudo make install
# Bash completion
sudo cp contrib/completion/git-completion.bash /etc/bash_completion.d/git
# Man pages
info "Downloading git-manpages-${version}.tar.gz"
curl -sS -O "https://www.kernel.org/pub/software/scm/git/git-manpages-${version}.tar.gz"
info "Extracting git-manpages-${version}.tar.gz"
sudo mkdir -p /usr/local/share/man
sudo tar zxvf "git-manpages-${version}.tar.gz" -C /usr/local/share/man
info "Done"

echo
