#!/bin/bash

function update_git_repo() {
    local repo="$1"
    git -C "$repo" pull
}

function update_file() {
    local url="$1" outfile="$2" perms="${3:-644}"
    local sha1_pre sha1_post

    [ -f "$outfile" ] && sha1_pre="$(sha1sum "$outfile")"
    curl -sSL -o "$outfile" "$url"
    sha1_post="$(sha1sum "$outfile")"
    [ "$sha1_pre" != "$sha1_post" ] && echo -e "\e[32;1mUpdated:\e[0m $outfile\n"
    chmod "$perms" "$outfile"
}

# Sublime Shell Syntax
update_file https://raw.githubusercontent.com/jfcherng/Packages/fix-shell/ShellScript/Shell-Unix-Generic.sublime-syntax \
            "$HOME/.config/sublime-text-3/Packages/ShellScript/Shell-Unix-Generic.sublime-syntax"

# Git Rebaser
update_file https://gist.githubusercontent.com/koreno/5893d2d969ccb6b8341d/raw/rebaser.py \
            "$HOME/bin/rebaser.py" \
            755

# jq
update_file http://stedolan.github.io/jq/download/linux64/jq \
            "$HOME/bin/jq" \
            755

# Font "bront"
update_git_repo "$HOME/.fonts/bront"

# Neovim
sudo apt-get --only-upgrade -y install neovim &

# Shellcheck
cabal update && cabal install shellcheck
