#!/bin/bash

set -e

function update_git_repo() {
    local repo="$1" exit_status=0
    git -C "$repo" pull -q
    exit_status="$?"
    [ "$exit_status" != 0 ] && echo -e "\e[32;1mUpdated:\e[0m $repo\n"
    return $exit_status
}

function update_file() {
    local url="$1" outfile="$2" perms="${3:-644}"
    local sha1_pre sha1_post

    [ -f "$outfile" ] && sha1_pre="$(sha1sum "$outfile")"
    curl -sSL -o "$outfile" "$url"
    sha1_post="$(sha1sum "$outfile")"
    [ "$sha1_pre" != "$sha1_post" ] && echo -e "\e[32;1mUpdated:\e[0m $outfile\n"
    chmod "$perms" "$outfile"
}

# Prompt for sudo password before doing anything
sudo -v

# Resynchronize the apt package index files from their sources
sudo apt-get update

# Rubygems
sudo gem update &

# jq
# update_file http://stedolan.github.io/jq/download/linux64/jq \
#             "$HOME/bin/jq" \
#             755

# Fuzzy Finder
update_git_repo "$HOME/.fzf"
yes y | ~/.fzf/install >/dev/null

# TMUX Plugin Manager
for plugin in ~/.tmux/plugins/*; do
    update_git_repo "$plugin"
done

# moreutils
MOREUTILS_DIR=/space/tools/moreutils
update_git_repo "/space/tools/moreutils"
if [ $? -ne 0 ]; then
    cd "$MOREUTILS_DIR"
    make && sudo make install
fi

# Neovim + fish
sudo apt-get --only-upgrade -y install neovim fish &

# Shellcheck
cabal update && cabal install shellcheck
